import type { LanguageKeys } from "static/languages";
import type { BaseFormType, BaseType, DocumentId } from "./common/base_type";
import type { StrapiConnect } from "./common/StrapiQuery";
import type { Contact } from "./contact";
import type { Frequency } from "./frequncy";
import type { Industry } from "./industry";
import type { MediaType } from "./media-type";
import type { OrganizationType } from "./organization-type";
import type { Source } from "./source";
import type { Tag } from "./tag";
export interface Organization extends BaseType {
	email: string;
	contacts: Contact[];
	address_line1: string;
	contact_person: string;
	location: string;
	frequency: Frequency;
	media_type: MediaType;
	zip: string;
	country: string;
	url: string;
	organization_type: OrganizationType;
	twitter_url: string;
	facebook_url: string;
	whatsapp_channel: string;
	linkedin_url: string;
	telegram_url: string;
	telegram_channel: string;
	instagram_url: string;
	tiktok_url: string;
	whatsapp_phone: string;
	phone: string;
	tags: Tag[];
	description: string;
	canton: string;
	language: LanguageKeys;
	sources: Source;
	industry: Industry;
	city: string;
	company_size: string;
}

export interface Form_Organization extends BaseFormType {
	email: string;
	contacts: StrapiConnect;
	address_line1: string;
	contact_person: string;
	location: string;
	frequency: DocumentId;
	media_type: DocumentId;
	zip: string;
	country: string;
	url: string;
	organization_type: DocumentId;
	twitter_url: string;
	facebook_url: string;
	whatsapp_channel: string;
	linkedin_url: string;
	telegram_url: string;
	telegram_channel: string;
	instagram_url: string;
	tiktok_url: string;
	whatsapp_phone: string;
	phone: string;
	tags: StrapiConnect;
	description: string;
	canton: string;
	language: LanguageKeys;
	sources: DocumentId;
	industry: DocumentId;
	city: string;
	company_size: string;
}
