packages:
  - apps/*
  - libs/*
  - scripts/generate-app/templates/*

injectWorkspacePackages: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - unrs-resolver
  - esbuild
  - core-js
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@scarf/scarf'
