// AUTO-GENERATED BY scripts/generate-service-factory.ts. DO NOT EDIT MANUALLY.
import type BaseService from './base.service';
import { actionScoreItemsService } from '../action-score-items.service';
import { actionsService } from '../action.service';
import { actionTypeService } from '../action-type.service';
import { activityLogsService } from '../activity-logs.service';
import { campaignCategoriesService } from '../campaign-categories.service';
import { campaignsService } from '../campaigns.service';
import { channelsService } from '../channels.service';
import { composerService } from '../composer/composer.service';
import { compositionItemsService } from '../composition-items.service';
import { compositionScheduledsService } from '../composition-scheduleds.service';
import { compositionsService } from '../compositions.service';
import { consentsService } from '../consents.service';
import { contactDocumentsService } from '../contact-documents.service';
import { contactInterestsService } from '../contact-interests.service';
import { contactJobTitlesService } from '../contact-job-titles.service';
import { contactNotesService } from '../contact-notes.service';
import { contactRanksService } from '../contact-ranks.service';
import { contactSalutationsService } from '../contact-salutations.service';
import { contactsService } from '../contacts.service';
import { contactTitlesService } from '../contact-titles.service';
import { contactTypesService } from '../contact-types.service';
import { dalService } from '../dal/dal.service';
import { departmentsService } from '../departments.service';
import { donationSubscriptionsService } from '../donation-subscriptions.service';
import { donationTransactionsService } from '../donation-transactions.service';
import { eventsService } from '../events.service';
import { formItemsService } from '../form-items.service';
import { formsService } from '../forms.service';
import { frequenciesService } from '../frequencies.service';
import { identitiesService } from '../identities.service';
import { industriesService } from '../industries.service';
import { journeyPassedStepService } from '../journey-passed-step.service';
import { journeysService } from '../journeys.service';
import { journeyStepConnectionsService } from '../journey-step-connection.service';
import { journeyStepRuleScoresService } from '../journey-step-rule-score.service';
import { journeyStepRulesService } from '../journey-step-rules.service';
import { journeyStepsService } from '../journey-steps.service';
import { keywordsService } from '../keywords.service';
import { listsService } from '../lists.service';
import { mediaTypesService } from '../media-types.service';
import { organizationsService } from '../organizations.service';
import { organizationTypesService } from '../organization-types.service';
import { searchHistoriesService } from '../search-histories.service';
import { searchHistoryTemplatesService } from '../search-history-templates.service';
import { settingCredentialsService } from '../setting-credentials.service';
import { settingsService } from '../settings.service';
import { sourcesService } from '../sources.service';
import { subscriptionsService } from '../subscriptions.service';
import { subscriptionTypesService } from '../subscription-types.service';
import { surveyItemsService } from '../survey-items.service';
import { surveysService } from '../surveys.service';
import { tagsService } from '../tags.service';
import { tasksService } from '../tasks.service';
import { termsService } from '../terms.service';
import { textblocksService } from '../textblocks.service';
import { unipileIdentitiesService } from '../unipile-identities.service';
import { usersService } from '../users.service';

const BASE_SERVICE_NAMES = [
  'actionScoreItemsService',
  'actionsService',
  'actionTypeService',
  'activityLogsService',
  'campaignCategoriesService',
  'campaignsService',
  'channelsService',
  'compositionItemsService',
  'compositionScheduledsService',
  'compositionsService',
  'consentsService',
  'contactDocumentsService',
  'contactInterestsService',
  'contactJobTitlesService',
  'contactNotesService',
  'contactRanksService',
  'contactSalutationsService',
  'contactsService',
  'contactTitlesService',
  'contactTypesService',
  'departmentsService',
  'donationSubscriptionsService',
  'donationTransactionsService',
  'eventsService',
  'formItemsService',
  'formsService',
  'frequenciesService',
  'identitiesService',
  'industriesService',
  'journeyPassedStepService',
  'journeysService',
  'journeyStepConnectionsService',
  'journeyStepRuleScoresService',
  'journeyStepRulesService',
  'journeyStepsService',
  'keywordsService',
  'listsService',
  'mediaTypesService',
  'organizationsService',
  'organizationTypesService',
  'searchHistoriesService',
  'searchHistoryTemplatesService',
  'settingCredentialsService',
  'settingsService',
  'sourcesService',
  'subscriptionsService',
  'subscriptionTypesService',
  'surveyItemsService',
  'surveysService',
  'tagsService',
  'tasksService',
  'termsService',
  'textblocksService',
  'unipileIdentitiesService',
  'usersService',
] as const;

export type BaseServiceName = (typeof BASE_SERVICE_NAMES)[number];

const baseServices: Record<BaseServiceName, BaseService<unknown, unknown>> = {
  actionScoreItemsService,
  actionsService,
  actionTypeService,
  activityLogsService,
  campaignCategoriesService,
  campaignsService,
  channelsService,
  compositionItemsService,
  compositionScheduledsService,
  compositionsService,
  consentsService,
  contactDocumentsService,
  contactInterestsService,
  contactJobTitlesService,
  contactNotesService,
  contactRanksService,
  contactSalutationsService,
  contactsService,
  contactTitlesService,
  contactTypesService,
  departmentsService,
  donationSubscriptionsService,
  donationTransactionsService,
  eventsService,
  formItemsService,
  formsService,
  frequenciesService,
  identitiesService,
  industriesService,
  journeyPassedStepService,
  journeysService,
  journeyStepConnectionsService,
  journeyStepRuleScoresService,
  journeyStepRulesService,
  journeyStepsService,
  keywordsService,
  listsService,
  mediaTypesService,
  organizationsService,
  organizationTypesService,
  searchHistoriesService,
  searchHistoryTemplatesService,
  settingCredentialsService,
  settingsService,
  sourcesService,
  subscriptionsService,
  subscriptionTypesService,
  surveyItemsService,
  surveysService,
  tagsService,
  tasksService,
  termsService,
  textblocksService,
  unipileIdentitiesService,
  usersService,
};

const CUSTOM_SERVICE_NAMES = [
  'composerService',
  'dalService',
] as const;

export type CustomServiceName = (typeof CUSTOM_SERVICE_NAMES)[number];

const customServices = {
  composerService,
  dalService,
} as const;

const SERVICE_NAMES = [
  'actionScoreItemsService',
  'actionsService',
  'actionTypeService',
  'activityLogsService',
  'campaignCategoriesService',
  'campaignsService',
  'channelsService',
  'composerService',
  'compositionItemsService',
  'compositionScheduledsService',
  'compositionsService',
  'consentsService',
  'contactDocumentsService',
  'contactInterestsService',
  'contactJobTitlesService',
  'contactNotesService',
  'contactRanksService',
  'contactSalutationsService',
  'contactsService',
  'contactTitlesService',
  'contactTypesService',
  'dalService',
  'departmentsService',
  'donationSubscriptionsService',
  'donationTransactionsService',
  'eventsService',
  'formItemsService',
  'formsService',
  'frequenciesService',
  'identitiesService',
  'industriesService',
  'journeyPassedStepService',
  'journeysService',
  'journeyStepConnectionsService',
  'journeyStepRuleScoresService',
  'journeyStepRulesService',
  'journeyStepsService',
  'keywordsService',
  'listsService',
  'mediaTypesService',
  'organizationsService',
  'organizationTypesService',
  'searchHistoriesService',
  'searchHistoryTemplatesService',
  'settingCredentialsService',
  'settingsService',
  'sourcesService',
  'subscriptionsService',
  'subscriptionTypesService',
  'surveyItemsService',
  'surveysService',
  'tagsService',
  'tasksService',
  'termsService',
  'textblocksService',
  'unipileIdentitiesService',
  'usersService',
] as const;

export type ServiceName = (typeof SERVICE_NAMES)[number];

export function getService<T extends BaseServiceName>(serviceName: T): BaseService<unknown, unknown>;
export function getService<T extends CustomServiceName>(serviceName: T): (typeof customServices)[T];
export function getService(serviceName: ServiceName) {
  if (serviceName in baseServices) {
    return baseServices[serviceName as BaseServiceName];
  }

  const customService = customServices[serviceName as CustomServiceName];

  if (!customService) {
    throw new Error(`Unknown service: ${serviceName}`);
  }

  return customService;
}

export const ServiceFactory = {
  getService,
} as const;
