FROM node:22-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY . .

RUN corepack enable pnpm && pnpm i --frozen-lockfile

# Build arguments provided by CI/CD at build time
ARG DATABASE_URI
ARG PAYLOAD_SECRET

ENV DATABASE_URI=$DATABASE_URI
ENV PAYLOAD_SECRET=$PAYLOAD_SECRET

RUN pnpm --filter wiki generate:importmap && pnpm --filter wiki build

EXPOSE 3000
ENV NODE_ENV=production
ENV PORT=3000

CMD ["pnpm", "--filter", "wiki", "start"]