import type { BaseFormType, BaseType } from "../common/base_type";
import type { StrapiConnect } from "../common/StrapiQuery";
import type { Contact } from "./contact";
import type { Frequency } from "./frequency";
import type { Industry } from "./industry";
import type { MediaType } from "./media_type";
import type { OrganizationType } from "./organization_type";
import type { Source } from "./source";
import type { Tag } from "./tag";

export interface Organization extends BaseType {
	name: string;
	email: string;
	address_line1: string;
	contact_person: string;
	location: string;
	country: string;
	contacts: Contact[];
	frequency: Frequency;
	media_type: MediaType;
	zip: string;
	county: string;
	url: string;
	organization_type: OrganizationType;
	twitter_url: string;
	facebook_url: string;
	whatsapp_channel: string;
	linkedin_url: string;
	telegram_url: string;
	telegram_channel: string;
	instagram_url: string;
	tiktok_url: string;
	whatsapp_phone: string;
	tags: Tag[];
	description: string;
	canton: string;
	language: string;
	sources: Source[];
	industry: Industry;
}

export interface Form_Organization extends BaseFormType {
	name: string;
	email?: string;
	address_line1?: string;
	contact_person?: string;
	location?: string;
	country?: string;
	contacts?: StrapiConnect;
	frequency?: number;
	media_type?: number;
	zip?: string;
	county?: string;
	url?: string;
	organization_type?: number;
	twitter_url?: string;
	facebook_url?: string;
	whatsapp_channel?: string;
	linkedin_url?: string;
	telegram_url?: string;
	telegram_channel?: string;
	instagram_url?: string;
	tiktok_url?: string;
	whatsapp_phone?: string;
	tags?: StrapiConnect;
	description?: string;
	canton?: string;
	language?: string;
	sources?: StrapiConnect;
	industry?: number;
}
